import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'pt' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    // Header
    'nav.solutions': 'Soluções',
    'nav.products': 'Produtos', 
    'nav.home': 'Home',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato',
    'nav.support': 'Suporte',
    
    // Hero
    'hero.title': 'SIGLA',
    'hero.subtitle': 'Sistema Integrado',
    'hero.subtitle2': 'de Gestão de Linhas Aéreas',
    'hero.description': 'Centenas de empresas de transporte aéreo e rodoviário confiam no SIGLA para gerenciar suas operações, tripulação, frotas e carga com máxima eficiência.',
    'hero.cta1': 'Ver Demonstração',
    'hero.cta2': 'Conhecer Soluções',
    'hero.stats.companies': 'Empresas Atendidas',
    'hero.stats.experience': 'Anos de Experiência',
    'hero.stats.support': 'Suporte Técnico',
    
    // Solutions
    'solutions.title': 'Soluções',
    'solutions.subtitle': 'Sistemas integrados para cada tipo de operação de transporte',
    'solutions.completas': 'Completas',
    'solutions.aviation.title': 'SIGLA Aviação',
    'solutions.aviation.subtitle': 'Sistema Integrado de Gestão de Linhas Aéreas',
    'solutions.aviation.description': 'Solução completa para companhias aéreas, táxis aéreos e aviação executiva',
    'solutions.cargo.title': 'SIGLA Carga',
    'solutions.cargo.subtitle': 'Sistema Integrado de Gestão e Logística',
    'solutions.cargo.description': 'Soluções para empresas de transporte rodoviário de carga e passageiros',
    'solutions.crew.title': 'Gestão de Tripulantes',
    'solutions.crew.description': 'Controle completo de escalas, qualificações e disponibilidade',
    'solutions.scheduling.title': 'Programação Inteligente',
    'solutions.scheduling.description': 'Sistema avançado de planejamento e otimização de recursos',
    'solutions.docs.title': 'Documentação Digital',
    'solutions.docs.description': 'Gestão completa de documentos e certificações',
    'solutions.bi.title': 'Business Intelligence',
    'solutions.bi.description': 'Relatórios avançados e análises para tomada de decisão',
    'solutions.cta': 'Saiba Mais',
    'solutions.demo': 'Solicitar Demonstração Completa',
    
    // Features
    'features.flight.programming': 'Programação de voos',
    'features.crew.management': 'Gestão de tripulantes',
    'features.maintenance.control': 'Controle de manutenção',
    'features.operational.reports': 'Relatórios operacionais',
    'features.smart.routing': 'Roteirização inteligente',
    'features.driver.control': 'Controle de motoristas',
    'features.fleet.management': 'Gestão de frota',
    'features.realtime.monitoring': 'Monitoramento em tempo real',
    'features.automatic.scheduling': 'Escalas automáticas',
    'features.workday.control': 'Controle de jornada',
    'features.qualifications': 'Qualificações',
    'features.reserves.days.off': 'Reservas e folgas',
    'features.automatic.optimization': 'Otimização automática',
    'features.multiple.scenarios': 'Múltiplos cenários',
    'features.market.integration': 'Integração com mercado',
    'features.demand.forecasting': 'Previsões de demanda',
    'features.validity.control': 'Controle de validade',
    'features.automatic.alerts': 'Alertas automáticos',
    'features.secure.backup': 'Backup seguro',
    'features.mobile.access': 'Acesso mobile',
    'features.interactive.dashboards': 'Dashboards interativos',
    'features.custom.kpis': 'KPIs personalizados',
    'features.flexible.export': 'Exportação flexível',
    'features.predictive.analytics': 'Análises preditivas',
    
    // Clients
    'clients.title': 'Clientes que Confiam na SIGLA',
    'clients.subtitle': 'Empresas de aviação e logística que confiam em nossas soluções',
    'clients.testimonials.first.text': 'A SIGLA revolucionou nossa operação aérea. O sistema é intuitivo e oferece controle total sobre nossas operações.',
    'clients.testimonials.first.author': 'João Moreira',
    'clients.testimonials.first.position': 'Diretor de Operações, AeroTrans',
    'clients.testimonials.second.text': 'Com a SIGLA, conseguimos otimizar nossa logística de carga e reduzir custos operacionais significativamente.',
    'clients.testimonials.second.author': 'Maria Santos',
    'clients.testimonials.second.position': 'Gerente de Logística, CargoFast',
    
    // Contact
    'contact.title': 'Entre em Contato',
    'contact.subtitle': 'Entre em contato e descubra como a SIGLA pode otimizar suas operações',
    'contact.form.title': 'Formulário de Contato',
    'contact.form.name': 'Nome',
    'contact.form.namePlaceholder': 'Digite seu nome',
    'contact.form.company': 'Empresa',
    'contact.form.companyPlaceholder': 'Digite o nome da empresa',
    'contact.form.email': 'E-mail',
    'contact.form.emailPlaceholder': 'Digite seu e-mail',
    'contact.form.phone': 'Telefone',
    'contact.form.phonePlaceholder': 'Digite seu telefone',
    'contact.form.segment': 'Segmento',
    'contact.form.segmentPlaceholder': 'Selecione o segmento',
    'contact.form.message': 'Mensagem',
    'contact.form.messagePlaceholder': 'Digite sua mensagem',
    'contact.form.send': 'Enviar Mensagem',
    'contact.form.submit': 'Enviar',
    'contact.form.response': 'Obrigado! Sua mensagem foi enviada com sucesso.',
    'contact.info.phone': 'Telefone',
    'contact.info.email': 'E-mail',
    'contact.info.address': 'Endereço',
    'contact.info.hours': 'Horário de Funcionamento',
    
    // About Page
    'about.hero.title': 'Sobre a LATOP',
    'about.hero.subtitle': '15 anos transformando o futuro do transporte através da inovação tecnológica',
    'about.mission.title': 'Nossa Missão',
    'about.mission.description': 'Desenvolver soluções tecnológicas inovadoras que otimizem operações de transporte, aumentando a eficiência e reduzindo custos para nossos clientes.',
    'about.vision.title': 'Nossa Visão',
    'about.vision.description': 'Ser a empresa líder em soluções integradas de gestão para o setor de transporte na América Latina até 2030.',
    'about.values.title': 'Nossos Valores',
    'about.values.description': 'Inovação, excelência, confiabilidade e sustentabilidade guiam todas as nossas decisões e desenvolvimentos.',
    'about.values.innovation.title': 'Inovação',
    'about.values.innovation.description': 'Sempre em busca das mais avançadas tecnologias para otimizar operações de transporte',
    'about.values.excellence.title': 'Excelência',
    'about.values.excellence.description': 'Comprometimento com a qualidade e satisfação total dos nossos clientes',
    'about.values.reliability.title': 'Confiabilidade',
    'about.values.reliability.description': 'Sistemas robustos e seguros que garantem operações 24/7 sem interrupções',
    'about.values.sustainability.title': 'Sustentabilidade',
    'about.values.sustainability.description': 'Soluções que promovem eficiência operacional e redução de impacto ambiental',
    'about.history.title': 'Nossa História',
    'about.history.subtitle': 'Uma jornada de inovação e crescimento no setor de transporte',
    'about.timeline.2009.title': 'Fundação da LATOP',
    'about.timeline.2009.description': 'Início das atividades focadas em soluções logísticas para transporte',
    'about.timeline.2012.title': 'Lançamento do SIGLA',
    'about.timeline.2012.description': 'Primeiro sistema integrado para gestão de linhas aéreas',
    'about.timeline.2015.title': 'Expansão para Carga',
    'about.timeline.2015.description': 'Desenvolvimento do módulo SIGLA Carga para transporte rodoviário',
    'about.timeline.2018.title': '100 Clientes',
    'about.timeline.2018.description': 'Marco de 100 empresas utilizando nossas soluções',
    'about.timeline.2021.title': 'Certificação ISO',
    'about.timeline.2021.description': 'Obtenção de certificações internacionais de qualidade',
    'about.timeline.2024.title': '200+ Empresas',
    'about.timeline.2024.description': 'Mais de 200 empresas confiam em nossas soluções',
    'about.stats.title': 'Números que Impressionam',
    'about.stats.companies': 'Empresas Atendidas',
    'about.stats.experience': 'Anos de Experiência',
    'about.stats.flights': 'Voos Gerenciados/Mês',
    'about.stats.uptime': 'Uptime Garantido',
    'about.team.title': 'Nossa Equipe',
    'about.team.description': 'Contamos com mais de 50 profissionais especializados em desenvolvimento de software, engenharia de sistemas, gestão de projetos e suporte técnico.',
    'about.team.specialists': '50+ Especialistas',
    'about.team.support': 'Suporte 24/7',
    'about.team.certifications': 'Certificações Internacionais',
    'about.location.title': 'Nossa Localização',
    'about.location.description': 'Sediados em São Paulo, no coração do maior centro financeiro e empresarial do Brasil, estamos estrategicamente posicionados para atender toda a América Latina.',
    'about.location.headquarters': 'Sede Principal',
    'about.location.address': 'Av. Paulista, 1000 - São Paulo/SP',
    'about.location.development': 'Centro de Desenvolvimento',
    'about.location.area': '3.000m² de área dedicada à inovação',
    
    // Footer
    'footer.description': 'Sistema integrado para gestão completa de operações de transporte aéreo e rodoviário.',
    'footer.solutions': 'Soluções',
    'footer.company': 'Empresa',
    'footer.links.aviation': 'SIGLA Aviação',
    'footer.links.cargo': 'SIGLA Carga',
    'footer.links.crew': 'Gestão de Tripulantes',
    'footer.links.bi': 'Business Intelligence',
    'footer.links.docs': 'Documentação Digital',
    'footer.links.about': 'Sobre Nós',
    'footer.links.clients': 'Clientes',
    'footer.links.careers': 'Carreiras',
    'footer.links.blog': 'Blog',
    'footer.links.contact': 'Contato',
    'footer.links.privacy': 'Política de Privacidade',
    'footer.links.terms': 'Termos de Serviço',
    'footer.links.support': 'Suporte',
    'footer.copyright': '© 2024 LATOP - Sistema Integrado de Gestão de Linhas Aéreas. Todos os direitos reservados.',
    
    // Pages
    'pages.aviation.title': 'SIGLA Aviação',
    'pages.cargo.title': 'SIGLA Carga',
    'pages.about.title': 'Sobre Nós',
    'pages.contact.title': 'Contato',
    'pages.products.title': 'Produtos',
  },
  en: {
    // Header
    'nav.solutions': 'Solutions',
    'nav.products': 'Products',
    'nav.home': 'Home', 
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.support': 'Support',
    
    // Hero
    'hero.title': 'SIGLA',
    'hero.subtitle': 'Integrated System',
    'hero.subtitle2': 'for Airline Management',
    'hero.description': 'Hundreds of air and road transport companies trust SIGLA to manage their operations, crew, fleets and cargo with maximum efficiency.',
    'hero.cta1': 'Watch Demo',
    'hero.cta2': 'Discover Solutions',
    'hero.stats.companies': 'Companies Served',
    'hero.stats.experience': 'Years of Experience',
    'hero.stats.support': 'Technical Support',
    
    // Solutions
    'solutions.title': 'Solutions',
    'solutions.subtitle': 'Integrated systems for every type of transport operation',
    'solutions.completas': 'Complete',
    'solutions.aviation.title': 'SIGLA Aviation',
    'solutions.aviation.subtitle': 'Integrated Airline Management System',
    'solutions.aviation.description': 'Complete solution for airlines, air taxis and executive aviation',
    'solutions.cargo.title': 'SIGLA Cargo',
    'solutions.cargo.subtitle': 'Integrated Management and Logistics System',
    'solutions.cargo.description': 'Solutions for road freight and passenger transport companies',
    'solutions.crew.title': 'Crew Management',
    'solutions.crew.description': 'Complete control of schedules, qualifications and availability',
    'solutions.scheduling.title': 'Smart Scheduling',
    'solutions.scheduling.description': 'Advanced system for resource planning and optimization',
    'solutions.docs.title': 'Digital Documentation',
    'solutions.docs.description': 'Complete management of documents and certifications',
    'solutions.bi.title': 'Business Intelligence',
    'solutions.bi.description': 'Advanced reports and analytics for decision making',
    'solutions.cta': 'Learn More',
    'solutions.demo': 'Request Complete Demo',
    
    // Features
    'features.flight.programming': 'Flight programming',
    'features.crew.management': 'Crew management',
    'features.maintenance.control': 'Maintenance control',
    'features.operational.reports': 'Operational reports',
    'features.smart.routing': 'Smart routing',
    'features.driver.control': 'Driver control',
    'features.fleet.management': 'Fleet management',
    'features.realtime.monitoring': 'Real-time monitoring',
    'features.automatic.scheduling': 'Automatic scheduling',
    'features.workday.control': 'Workday control',
    'features.qualifications': 'Qualifications',
    'features.reserves.days.off': 'Reserves and days off',
    'features.automatic.optimization': 'Automatic optimization',
    'features.multiple.scenarios': 'Multiple scenarios',
    'features.market.integration': 'Market integration',
    'features.demand.forecasting': 'Demand forecasting',
    'features.validity.control': 'Validity control',
    'features.automatic.alerts': 'Automatic alerts',
    'features.secure.backup': 'Secure backup',
    'features.mobile.access': 'Mobile access',
    'features.interactive.dashboards': 'Interactive dashboards',
    'features.custom.kpis': 'Custom KPIs',
    'features.flexible.export': 'Flexible export',
    'features.predictive.analytics': 'Predictive analytics',
    
    // Clients
    'clients.title': 'Clients Who Trust SIGLA',
    'clients.subtitle': 'Aviation and logistics companies that trust our solutions',
    'clients.testimonials.first.text': 'SIGLA revolutionized our aviation operation. The system is intuitive and offers complete control over our operations.',
    'clients.testimonials.first.author': 'John Morrison',
    'clients.testimonials.first.position': 'Operations Director, AeroTrans',
    'clients.testimonials.second.text': 'With SIGLA, we managed to optimize our cargo logistics and significantly reduce operational costs.',
    'clients.testimonials.second.author': 'Mary Santos',
    'clients.testimonials.second.position': 'Logistics Manager, CargoFast',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch and discover how SIGLA can optimize your operations',
    'contact.form.title': 'Contact Form',
    'contact.form.name': 'Name',
    'contact.form.namePlaceholder': 'Enter your name',
    'contact.form.company': 'Company',
    'contact.form.companyPlaceholder': 'Enter company name',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'Enter your email',
    'contact.form.phone': 'Phone',
    'contact.form.phonePlaceholder': 'Enter your phone',
    'contact.form.segment': 'Segment',
    'contact.form.segmentPlaceholder': 'Select segment',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Enter your message',
    'contact.form.send': 'Send Message',
    'contact.form.submit': 'Submit',
    'contact.form.response': 'Thank you! Your message has been sent successfully.',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.address': 'Address',
    'contact.info.hours': 'Business Hours',
    
    // About Page
    'about.hero.title': 'About LATOP',
    'about.hero.subtitle': '15 years transforming the future of transport through technological innovation',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'Develop innovative technological solutions that optimize transport operations, increasing efficiency and reducing costs for our clients.',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'To be the leading company in integrated management solutions for the transport sector in Latin America by 2030.',
    'about.values.title': 'Our Values',
    'about.values.description': 'Innovation, excellence, reliability and sustainability guide all our decisions and developments.',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.description': 'Always seeking the most advanced technologies to optimize transport operations',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.description': 'Commitment to quality and total satisfaction of our clients',
    'about.values.reliability.title': 'Reliability',
    'about.values.reliability.description': 'Robust and secure systems that guarantee 24/7 operations without interruptions',
    'about.values.sustainability.title': 'Sustainability',
    'about.values.sustainability.description': 'Solutions that promote operational efficiency and reduce environmental impact',
    'about.history.title': 'Our History',
    'about.history.subtitle': 'A journey of innovation and growth in the transport sector',
    'about.timeline.2009.title': 'LATOP Foundation',
    'about.timeline.2009.description': 'Beginning of activities focused on logistics solutions for transport',
    'about.timeline.2012.title': 'SIGLA Launch',
    'about.timeline.2012.description': 'First integrated system for airline management',
    'about.timeline.2015.title': 'Cargo Expansion',
    'about.timeline.2015.description': 'Development of SIGLA Cargo module for road transport',
    'about.timeline.2018.title': '100 Clients',
    'about.timeline.2018.description': 'Milestone of 100 companies using our solutions',
    'about.timeline.2021.title': 'ISO Certification',
    'about.timeline.2021.description': 'Obtaining international quality certifications',
    'about.timeline.2024.title': '200+ Companies',
    'about.timeline.2024.description': 'More than 200 companies trust our solutions',
    'about.stats.title': 'Impressive Numbers',
    'about.stats.companies': 'Companies Served',
    'about.stats.experience': 'Years of Experience',
    'about.stats.flights': 'Flights Managed/Month',
    'about.stats.uptime': 'Guaranteed Uptime',
    'about.team.title': 'Our Team',
    'about.team.description': 'We have more than 50 professionals specialized in software development, systems engineering, project management and technical support.',
    'about.team.specialists': '50+ Specialists',
    'about.team.support': '24/7 Support',
    'about.team.certifications': 'International Certifications',
    'about.location.title': 'Our Location',
    'about.location.description': 'Based in São Paulo, in the heart of Brazil\'s largest financial and business center, we are strategically positioned to serve all of Latin America.',
    'about.location.headquarters': 'Main Headquarters',
    'about.location.address': 'Av. Paulista, 1000 - São Paulo/SP',
    'about.location.development': 'Development Center',
    'about.location.area': '3,000m² of area dedicated to innovation',
    
    // Footer
    'footer.description': 'Integrated system for complete management of air and road transport operations.',
    'footer.solutions': 'Solutions',
    'footer.company': 'Company',
    'footer.links.aviation': 'SIGLA Aviation',
    'footer.links.cargo': 'SIGLA Cargo',
    'footer.links.crew': 'Crew Management',
    'footer.links.bi': 'Business Intelligence',
    'footer.links.docs': 'Digital Documentation',
    'footer.links.about': 'About Us',
    'footer.links.clients': 'Clients',
    'footer.links.careers': 'Careers',
    'footer.links.blog': 'Blog',
    'footer.links.contact': 'Contact',
    'footer.links.privacy': 'Privacy Policy',
    'footer.links.terms': 'Terms of Service',
    'footer.links.support': 'Support',
    'footer.copyright': '© 2024 LATOP - Integrated Airline Management System. All rights reserved.',
    
    // Pages
    'pages.aviation.title': 'SIGLA Aviation',
    'pages.cargo.title': 'SIGLA Cargo',
    'pages.about.title': 'About Us',
    'pages.contact.title': 'Contact',
    'pages.products.title': 'Products',
  },
  es: {
    // Header
    'nav.solutions': 'Soluciones',
    'nav.products': 'Productos',
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    'nav.support': 'Soporte',
    
    // Hero
    'hero.title': 'SIGLA',
    'hero.subtitle': 'Sistema Integrado',
    'hero.subtitle2': 'de Gestión de Líneas Aéreas',
    'hero.description': 'Cientos de empresas de transporte aéreo y terrestre confían en SIGLA para gestionar sus operaciones, tripulación, flotas y carga con máxima eficiencia.',
    'hero.cta1': 'Ver Demostración',
    'hero.cta2': 'Descubrir Soluciones',
    'hero.stats.companies': 'Empresas Atendidas',
    'hero.stats.experience': 'Años de Experiencia',
    'hero.stats.support': 'Soporte Técnico',
    
    // Solutions
    'solutions.title': 'Soluciones',
    'solutions.subtitle': 'Sistemas integrados para cada tipo de operación de transporte',
    'solutions.completas': 'Completas',
    'solutions.aviation.title': 'SIGLA Aviación',
    'solutions.aviation.subtitle': 'Sistema Integrado de Gestión de Líneas Aéreas',
    'solutions.aviation.description': 'Solución completa para aerolíneas, taxis aéreos y aviación ejecutiva',
    'solutions.cargo.title': 'SIGLA Carga',
    'solutions.cargo.subtitle': 'Sistema Integrado de Gestión y Logística',
    'solutions.cargo.description': 'Soluciones para empresas de transporte terrestre de carga y pasajeros',
    'solutions.crew.title': 'Gestión de Tripulación',
    'solutions.crew.description': 'Control completo de horarios, calificaciones y disponibilidad',
    'solutions.scheduling.title': 'Programación Inteligente',
    'solutions.scheduling.description': 'Sistema avanzado de planificación y optimización de recursos',
    'solutions.docs.title': 'Documentación Digital',
    'solutions.docs.description': 'Gestión completa de documentos y certificaciones',
    'solutions.bi.title': 'Business Intelligence',
    'solutions.bi.description': 'Informes avanzados y análisis para toma de decisiones',
    'solutions.cta': 'Saber Más',
    'solutions.demo': 'Solicitar Demostración Completa',
    
    // Features
    'features.flight.programming': 'Programación de vuelos',
    'features.crew.management': 'Gestión de tripulación',
    'features.maintenance.control': 'Control de mantenimiento',
    'features.operational.reports': 'Informes operacionales',
    'features.smart.routing': 'Ruteo inteligente',
    'features.driver.control': 'Control de conductores',
    'features.fleet.management': 'Gestión de flota',
    'features.realtime.monitoring': 'Monitoreo en tiempo real',
    'features.automatic.scheduling': 'Programación automática',
    'features.workday.control': 'Control de jornada',
    'features.qualifications': 'Calificaciones',
    'features.reserves.days.off': 'Reservas y días libres',
    'features.automatic.optimization': 'Optimización automática',
    'features.multiple.scenarios': 'Múltiples escenarios',
    'features.market.integration': 'Integración con mercado',
    'features.demand.forecasting': 'Previsión de demanda',
    'features.validity.control': 'Control de validez',
    'features.automatic.alerts': 'Alertas automáticas',
    'features.secure.backup': 'Respaldo seguro',
    'features.mobile.access': 'Acceso móvil',
    'features.interactive.dashboards': 'Tableros interactivos',
    'features.custom.kpis': 'KPIs personalizados',
    'features.flexible.export': 'Exportación flexible',
    'features.predictive.analytics': 'Análisis predictivos',
    
    // Clients
    'clients.title': 'Clientes que Confían en SIGLA', 
    'clients.subtitle': 'Empresas de aviación y logística que confían en nuestras soluciones',
    'clients.testimonials.first.text': 'SIGLA revolucionó nuestra operación aérea. El sistema es intuitivo y ofrece control total sobre nuestras operaciones.',
    'clients.testimonials.first.author': 'João Moreira',
    'clients.testimonials.first.position': 'Director de Operaciones, AeroTrans',
    'clients.testimonials.second.text': 'Con SIGLA, logramos optimizar nuestra logística de carga y reducir significativamente los costos operacionales.',
    'clients.testimonials.second.author': 'María Santos',
    'clients.testimonials.second.position': 'Gerente de Logística, CargoFast',
    
    // Contact
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Ponte en contacto y descubre cómo SIGLA puede optimizar tus operaciones',
    'contact.form.title': 'Formulario de Contacto',
    'contact.form.name': 'Nombre',
    'contact.form.namePlaceholder': 'Ingresa tu nombre',
    'contact.form.company': 'Empresa',
    'contact.form.companyPlaceholder': 'Ingresa el nombre de la empresa',
    'contact.form.email': 'Correo',
    'contact.form.emailPlaceholder': 'Ingresa tu correo',
    'contact.form.phone': 'Teléfono',
    'contact.form.phonePlaceholder': 'Ingresa tu teléfono',
    'contact.form.segment': 'Segmento',
    'contact.form.segmentPlaceholder': 'Selecciona el segmento',
    'contact.form.message': 'Mensaje',
    'contact.form.messagePlaceholder': 'Ingresa tu mensaje',
    'contact.form.send': 'Enviar Mensaje',
    'contact.form.submit': 'Enviar',
    'contact.form.response': '¡Gracias! Tu mensaje ha sido enviado exitosamente.',
    'contact.info.phone': 'Teléfono',
    'contact.info.email': 'Correo',
    'contact.info.address': 'Dirección',
    'contact.info.hours': 'Horario de Atención',
    
    // About Page
    'about.hero.title': 'Acerca de LATOP',
    'about.hero.subtitle': '15 años transformando el futuro del transporte a través de la innovación tecnológica',
    'about.mission.title': 'Nuestra Misión',
    'about.mission.description': 'Desarrollar soluciones tecnológicas innovadoras que optimicen las operaciones de transporte, aumentando la eficiencia y reduciendo costos para nuestros clientes.',
    'about.vision.title': 'Nuestra Visión',
    'about.vision.description': 'Ser la empresa líder en soluciones integradas de gestión para el sector de transporte en América Latina para 2030.',
    'about.values.title': 'Nuestros Valores',
    'about.values.description': 'Innovación, excelencia, confiabilidad y sostenibilidad guían todas nuestras decisiones y desarrollos.',
    'about.values.innovation.title': 'Innovación',
    'about.values.innovation.description': 'Siempre buscando las tecnologías más avanzadas para optimizar las operaciones de transporte',
    'about.values.excellence.title': 'Excelencia',
    'about.values.excellence.description': 'Compromiso con la calidad y satisfacción total de nuestros clientes',
    'about.values.reliability.title': 'Confiabilidad',
    'about.values.reliability.description': 'Sistemas robustos y seguros que garantizan operaciones 24/7 sin interrupciones',
    'about.values.sustainability.title': 'Sostenibilidad',
    'about.values.sustainability.description': 'Soluciones que promueven eficiencia operacional y reducción del impacto ambiental',
    'about.history.title': 'Nuestra Historia',
    'about.history.subtitle': 'Un viaje de innovación y crecimiento en el sector del transporte',
    'about.timeline.2009.title': 'Fundación de LATOP',
    'about.timeline.2009.description': 'Inicio de actividades enfocadas en soluciones logísticas para transporte',
    'about.timeline.2012.title': 'Lanzamiento de SIGLA',
    'about.timeline.2012.description': 'Primer sistema integrado para gestión de líneas aéreas',
    'about.timeline.2015.title': 'Expansión a Carga',
    'about.timeline.2015.description': 'Desarrollo del módulo SIGLA Carga para transporte terrestre',
    'about.timeline.2018.title': '100 Clientes',
    'about.timeline.2018.description': 'Hito de 100 empresas utilizando nuestras soluciones',
    'about.timeline.2021.title': 'Certificación ISO',
    'about.timeline.2021.description': 'Obtención de certificaciones internacionales de calidad',
    'about.timeline.2024.title': '200+ Empresas',
    'about.timeline.2024.description': 'Más de 200 empresas confían en nuestras soluciones',
    'about.stats.title': 'Números que Impresionan',
    'about.stats.companies': 'Empresas Atendidas',
    'about.stats.experience': 'Años de Experiencia',
    'about.stats.flights': 'Vuelos Gestionados/Mes',
    'about.stats.uptime': 'Uptime Garantizado',
    'about.team.title': 'Nuestro Equipo',
    'about.team.description': 'Contamos con más de 50 profesionales especializados en desarrollo de software, ingeniería de sistemas, gestión de proyectos y soporte técnico.',
    'about.team.specialists': '50+ Especialistas',
    'about.team.support': 'Soporte 24/7',
    'about.team.certifications': 'Certificaciones Internacionales',
    'about.location.title': 'Nuestra Ubicación',
    'about.location.description': 'Con sede en São Paulo, en el corazón del mayor centro financiero y empresarial de Brasil, estamos estratégicamente posicionados para atender toda América Latina.',
    'about.location.headquarters': 'Sede Principal',
    'about.location.address': 'Av. Paulista, 1000 - São Paulo/SP',
    'about.location.development': 'Centro de Desarrollo',
    'about.location.area': '3.000m² de área dedicada a la innovación',
    
    // Footer
    'footer.description': 'Sistema integrado para gestión completa de operaciones de transporte aéreo y terrestre.',
    'footer.solutions': 'Soluciones',
    'footer.company': 'Empresa',
    'footer.links.aviation': 'SIGLA Aviación',
    'footer.links.cargo': 'SIGLA Carga',
    'footer.links.crew': 'Gestión de Tripulación',
    'footer.links.bi': 'Business Intelligence',
    'footer.links.docs': 'Documentación Digital',
    'footer.links.about': 'Acerca de Nosotros',
    'footer.links.clients': 'Clientes',
    'footer.links.careers': 'Carreras',
    'footer.links.blog': 'Blog',
    'footer.links.contact': 'Contacto',
    'footer.links.privacy': 'Política de Privacidad',
    'footer.links.terms': 'Términos de Servicio',
    'footer.links.support': 'Soporte',
    'footer.copyright': '© 2024 LATOP - Sistema Integrado de Gestión de Líneas Aéreas. Todos los derechos reservados.',
    
    // Pages
    'pages.aviation.title': 'SIGLA Aviación',
    'pages.cargo.title': 'SIGLA Carga', 
    'pages.about.title': 'Acerca de Nosotros',
    'pages.contact.title': 'Contacto',
    'pages.products.title': 'Productos',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};